package com.onlinelearning.service.impl;
import com.onlinelearning.config.*; import com.onlinelearning.dto.auth.*; import com.onlinelearning.entity.*; import com.onlinelearning.exception.*; import com.onlinelearning.api.EmailGateway; import com.onlinelearning.repository.*; import com.onlinelearning.service.*; import lombok.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.security.core.authority.*; import org.springframework.security.crypto.password.*; import org.springframework.stereotype.*; import org.springframework.transaction.annotation.*; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor @Transactional public class AuthServiceImpl implements AuthService {
 private final UserRepository users; private final RoleRepository roles; private final PasswordResetTokenRepository resetTokens; private final PasswordEncoder encoder; private final JwtTokenProvider jwt; private final EmailGateway emailGateway;
 @Value("${app.frontend-url}") private String frontendUrl;
 public TokenResponse login(LoginRequest r){User u=users.findByEmailIgnoreCase(r.email()).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"Invalid email or password"));if(!u.isEnabled()||u.isBlocked())throw new ApiException(HttpStatus.FORBIDDEN,"Account is inactive or blocked");if(!encoder.matches(r.password(),u.getPasswordHash()))throw new ApiException(HttpStatus.UNAUTHORIZED,"Invalid email or password");return tokens(u);}
 public void register(RegisterRequest r){if(users.existsByEmailIgnoreCase(r.email()))throw new ApiException(HttpStatus.CONFLICT,"Email already registered");Role student=roles.findByCode("STUDENT").orElseThrow(()->new ApiException(HttpStatus.INTERNAL_SERVER_ERROR,"Roles have not been initialized"));User u=new User();u.setEmail(r.email().toLowerCase());u.setFullName(r.fullName());u.setPasswordHash(encoder.encode(r.password()));u.getRoles().add(student);users.save(u);}
 public TokenResponse refresh(RefreshRequest r){if(!jwt.valid(r.refreshToken()))throw new ApiException(HttpStatus.UNAUTHORIZED,"Invalid refresh token");return tokens(users.findByEmailIgnoreCase(jwt.subject(r.refreshToken())).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"User not found")));}
 public void forgotPassword(ForgotPasswordRequest r){users.findByEmailIgnoreCase(r.email()).ifPresent(u->{PasswordResetToken t=new PasswordResetToken();t.setUser(u);t.setToken(UUID.randomUUID().toString());t.setExpiresAt(Instant.now().plus(Duration.ofMinutes(30)));resetTokens.save(t);emailGateway.sendPasswordReset(u.getEmail(),frontendUrl + "/reset-password?token=" + t.getToken());});}
 public void resetPassword(ResetPasswordRequest r){PasswordResetToken token=resetTokens.findByToken(r.token()).orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"Invalid reset token"));if(token.getUsedAt()!=null||token.getExpiresAt().isBefore(Instant.now()))throw new ApiException(HttpStatus.BAD_REQUEST,"Reset token has expired");token.getUser().setPasswordHash(encoder.encode(r.newPassword()));token.setUsedAt(Instant.now());}
 private TokenResponse tokens(User u){var a=u.getRoles().stream().map(r->new SimpleGrantedAuthority(r.authority())).toList();var names=u.getRoles().stream().map(Role::authority).collect(java.util.stream.Collectors.toSet());return new TokenResponse(jwt.accessToken(u.getEmail(),a),jwt.refreshToken(u.getEmail()),"Bearer",u.getId(),u.getEmail(),names);}
}
