package com.onlinelearning.config;
import com.onlinelearning.repository.UserRepository; import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.*; import org.springframework.context.annotation.*; import org.springframework.security.config.annotation.web.builders.*; import org.springframework.security.config.annotation.web.configuration.*; import org.springframework.security.config.http.*; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.security.core.userdetails.*; import org.springframework.security.crypto.bcrypt.*; import org.springframework.security.crypto.password.*; import org.springframework.security.web.*; import org.springframework.security.web.authentication.*; import org.springframework.web.cors.*; import java.util.*;
@Configuration @EnableWebSecurity @RequiredArgsConstructor public class SecurityConfig {
 private final JwtAuthenticationFilter jwtFilter; private final UserRepository users; @Value("${app.cors.allowed-origins}") private String origins;
 @Bean SecurityFilterChain security(HttpSecurity http)throws Exception{return http.csrf(c->c.disable()).cors(c->c.configurationSource(cors())).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).exceptionHandling(e->e.authenticationEntryPoint((r,p,x)->p.sendError(401,"Authentication required")).accessDeniedHandler((r,p,x)->p.sendError(403,"Access denied"))).authorizeHttpRequests(a->a.requestMatchers("/api/v1/auth/**","/swagger-ui/**","/v3/api-docs/**","/api/v1/public/**").permitAll().requestMatchers("/api/v1/admin/**").hasRole("ADMIN").requestMatchers("/api/v1/manager/**").hasRole("MANAGER").requestMatchers("/api/v1/expert/**").hasRole("EXPERT").requestMatchers("/api/v1/student/**").hasRole("STUDENT").anyRequest().authenticated()).addFilterBefore(jwtFilter,UsernamePasswordAuthenticationFilter.class).build();}
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 @Bean UserDetailsService userDetailsService(){return email -> users.findByEmailIgnoreCase(email).map(user -> User.withUsername(user.getEmail()).password(user.getPasswordHash()).disabled(!user.isEnabled()).accountLocked(user.isBlocked()).authorities(user.getRoles().stream().map(role -> new SimpleGrantedAuthority(role.authority())).toList()).build()).orElseThrow(() -> new UsernameNotFoundException("User not found"));}
 @Bean CorsConfigurationSource cors(){var c=new CorsConfiguration();c.setAllowedOrigins(Arrays.asList(origins.split(",")));c.setAllowedMethods(List.of("GET","POST","PUT","PATCH","DELETE","OPTIONS"));c.setAllowedHeaders(List.of("Authorization","Content-Type"));var s=new UrlBasedCorsConfigurationSource();s.registerCorsConfiguration("/**",c);return s;}
}
